export default {
  logo: require('./logo.png'),
  topTitle: require('./topTitle.png'),
  background: require('./background.png'),
  defaultUser: require('./default-user.png'),
  iconApes2: require('./icon-apes2.png'),
  iconArrowLeft: require('./icon-arrow-left.png'),
  iconAvatar: require('./icon-avatar.png'),
  iconChat: require('./icon-chat.png'),
  iconCoin: require('./icon-coin.png'),
  iconMatic: require('./icon-matic.png'),
  iconNotify: require('./icon-notify.png'),
  iconLogout: require('./icon-logout.png'),
  iconProfile: require('./icon-profile.png'),
};
